language: go
os: linux
dist: xenial
go: "1.14"

jobs:
  include:
    - name: "Unit Tests"
      script: go test -race -coverprofile=coverage.txt -covermode=atomic
      after_success: bash <(curl -s https://codecov.io/bash)
    - name: "E2E Tests - 6.2.1"
      script: ./e2e.sh 6.2.1 5.0 0 0
    - name: "E2E Tests - 6.2.1 (AUTH)"
      script: ./e2e.sh 6.2.1 5.0 1 0
    - name: "E2E Tests - 5.0.12"
      script: ./e2e.sh 5.0.12 5.0 0 0
    - name: "E2E Tests - 5.0.12 (AUTH from File)"
      script: ./e2e.sh 5.0.12 5.0 1 1
    - name: "E2E Tests - 4.0.14"
      script: ./e2e.sh 4.0.14 3.2 0 0
    - name: "E2E Tests - 3.2.13"
      script: ./e2e.sh 3.2.13 3.2 0 0
    - name: "E2E Tests - 3.0.7"
      script: ./e2e.sh 3.0.7 3.0 0 0
